services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./mysql_data:/var/lib/mysql
  myadmin:
    image: phpmyadmin
    links:
      - mysql:db
    ports:
      - "8080:80"

